name: fact-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip=24.2.0
  - pytorch-cuda=11.8
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pandas==2.3.3
  - matplotlib==3.10.7
  - plotly==3.0.52
  - nbformat==5.10.4
  - pip:
      - accelerate==1.12.0
      - bidict==0.23.1
      - datasets==4.4.2
      - einops==0.8.1
      - jaxtyping==0.3.5
      - kornia==0.8.2
      - nnsight==0.5.14
      - transformers==4.57.3
      - wandb==0.23.1
      - scipy==1.16.3